UNIVERSIDAD GALILEO

STATISTICAL LEARNING

Marco Vinicio Escalante Lara

Carnet: 19001148


# Mediciones dimensionales

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

## Generamos Matrices

Desarrollamos una matriz de 5x2

In [2]:
X = np.random.randn(5,2)
X

array([[ 0.76537193, -0.431293  ],
       [-1.58095306, -0.69002598],
       [-0.52806565, -1.19871085],
       [-0.22849971,  1.78533258],
       [-0.13856311, -0.04613277]])

In [3]:
X.shape

(5, 2)

## Matriz con grado 2

Desarrollamos la matriz que tenemos en la primera parte y desarrollamos una nueva matriz con mayor tamaño, en este caso de grado 2.

In [5]:
poly = PolynomialFeatures(degree=2)
X_grado2 = poly.fit_transform(X)
X_grado2

array([[ 1.00000000e+00,  7.65371932e-01, -4.31293005e-01,
         5.85794194e-01, -3.30099560e-01,  1.86013656e-01],
       [ 1.00000000e+00, -1.58095306e+00, -6.90025981e-01,
         2.49941258e+00,  1.09089869e+00,  4.76135855e-01],
       [ 1.00000000e+00, -5.28065650e-01, -1.19871085e+00,
         2.78853331e-01,  6.32998023e-01,  1.43690769e+00],
       [ 1.00000000e+00, -2.28499706e-01,  1.78533258e+00,
         5.22121156e-02, -4.07947970e-01,  3.18741242e+00],
       [ 1.00000000e+00, -1.38563113e-01, -4.61327652e-02,
         1.91997364e-02,  6.39229957e-03,  2.12823203e-03]])

In [6]:
X_grado2.shape

(5, 6)

## Matriz con grado 3

Desarrollamos la matriz que tenemos en la primera parte y desarrollamos una nueva matriz con mayor tamaño, en este caso de grado 3.

In [8]:
poly = PolynomialFeatures(degree=3)
X_grado3 = poly.fit_transform(X)
X_grado3

array([[ 1.00000000e+00,  7.65371932e-01, -4.31293005e-01,
         5.85794194e-01, -3.30099560e-01,  1.86013656e-01,
         4.48350434e-01, -2.52648938e-01,  1.42369631e-01,
        -8.02263885e-02],
       [ 1.00000000e+00, -1.58095306e+00, -6.90025981e-01,
         2.49941258e+00,  1.09089869e+00,  4.76135855e-01,
        -3.95145396e+00, -1.72465962e+00, -7.52748436e-01,
        -3.28546110e-01],
       [ 1.00000000e+00, -5.28065650e-01, -1.19871085e+00,
         2.78853331e-01,  6.32998023e-01,  1.43690769e+00,
        -1.47252866e-01, -3.34264512e-01, -7.58781596e-01,
        -1.72243684e+00],
       [ 1.00000000e+00, -2.28499706e-01,  1.78533258e+00,
         5.22121156e-02, -4.07947970e-01,  3.18741242e+00,
        -1.19304531e-02,  9.32159911e-02, -7.28322801e-01,
         5.69059125e+00],
       [ 1.00000000e+00, -1.38563113e-01, -4.61327652e-02,
         1.91997364e-02,  6.39229957e-03,  2.12823203e-03,
        -2.66037524e-03, -8.85736930e-04, -2.94894456e-04,
        -9.

In [9]:
X_grado3.shape

(5, 10)

## Matriz con grado 10

Desarrollamos la matriz que tenemos en la primera parte y desarrollamos una nueva matriz con mayor tamaño, en este caso de grado 10.

In [10]:
poly = PolynomialFeatures(degree=10)
X_grado10 = poly.fit_transform(X)
X_grado10

array([[ 1.00000000e+00,  7.65371932e-01, -4.31293005e-01,
         5.85794194e-01, -3.30099560e-01,  1.86013656e-01,
         4.48350434e-01, -2.52648938e-01,  1.42369631e-01,
        -8.02263885e-02,  3.43154837e-01, -1.93370406e-01,
         1.08965720e-01, -6.14030260e-02,  3.46010802e-02,
         2.62641081e-01, -1.48000281e-01,  8.33993033e-02,
        -4.69961526e-02,  2.64826956e-02, -1.49232038e-02,
         2.01018111e-01, -1.13275261e-01,  6.38314858e-02,
        -3.59695361e-02,  2.02691119e-02, -1.14218013e-02,
         6.43627342e-03,  1.53853620e-01, -8.66977052e-02,
         4.88548276e-02, -2.75300733e-02,  1.55134093e-02,
        -8.74192615e-03,  4.92614302e-03, -2.77591970e-03,
         1.17755242e-01, -6.63559901e-02,  3.73921138e-02,
        -2.10707454e-02,  1.18735280e-02, -6.69082491e-03,
         3.77033160e-03, -2.12461102e-03,  1.19723475e-03,
         9.01265574e-02, -5.07870123e-02,  2.86188743e-02,
        -1.61269571e-02,  9.08766509e-03, -5.12096958e-0

In [11]:
X_grado10.shape

(5, 66)

## CONCLUSIONES

1. Permiten generar nuevas matrices a partir de un origen.
2. La nuevas matrices que se generan son transformaciones polinomiales de la original.
3. La cantidad de filas puede ser de cualquier largo, al igual que las columnas.
4. La cantidad de filas de las matrices generadas por la función tienen la misma cantidad de filas.
5. Las conlumnas que se generan tienen un orden de acuerdo al grado que se esta trabajando, para el caso de grado 2 se genara unas combinaciones con grado cuadrado, teniendo combinaciones de todos las variables.
6. Tiene gran utilidad ya que permite generar combinaciones de muchos números de manera casi instantanea.