In [1]:
import numpy as np

In [89]:
def funcion(x, peso):
    entrada = np.column_stack((x, np.ones(x.shape[0])))
    mult = np.matmul(entrada, peso)
    if mult.reshape(-1,1) > 0:
        salida = 1.
    else:
        salida = 0.
    return salida #activation(affine_transf(x, weights)).reshape(-1, 1)

In [90]:
funcion(np.array([[1., 1.]]), np.array([1., 1., 0]))

1.0

## Función AND

In [91]:
pesos = np.array([20., 20., -30.])
print("Entradas")
print(np.array([[1,1],[1,0],[0,1],[0,0]]))
print("Salidas")
print(funcion(np.array([[1,1]]),pesos))
print(funcion(np.array([[1,0]]),pesos))
print(funcion(np.array([[0,1]]),pesos))
print(funcion(np.array([[0,0]]),pesos))

Entradas
[[1 1]
 [1 0]
 [0 1]
 [0 0]]
Salidas
1.0
0.0
0.0
0.0


## Función OR

In [92]:
pesos = np.array([20., 20., -10.])
print("Entradas")
print(np.array([[1,1],[1,0],[0,1],[0,0]]))
print("Salidas")
print(funcion(np.array([[1,1]]),pesos))
print(funcion(np.array([[1,0]]),pesos))
print(funcion(np.array([[0,1]]),pesos))
print(funcion(np.array([[0,0]]),pesos))

Entradas
[[1 1]
 [1 0]
 [0 1]
 [0 0]]
Salidas
1.0
1.0
1.0
0.0


## Función NOT

In [93]:
pesos = np.array([-1., 0.5])
print("Entradas")
print(np.array([[0],[1]]))
print("Salidas")
print(funcion(np.array([[0]]),pesos))
print(funcion(np.array([[1]]),pesos))

Entradas
[[0]
 [1]]
Salidas
1.0
0.0


## Función XOR

In [94]:
peso_not = np.array([-1.,0.5])
peso_and = np.array([20., 20., -30.])
peso_or = np.array([20., 20., -10])

print("Entradas")
print(np.array([[1,1],[1,0],[0,1],[0,0]]))
print("Salidas")
X = np.array([1.,1.])
print(funcion(np.array([[funcion(np.array([[X[0],funcion(np.array([X[1]]),peso_not)]]),peso_and),
                         funcion(np.array([[funcion(np.array([X[0]]), peso_not),X[1]]]),peso_and)]]), peso_or))
X = np.array([1.,0.])
print(funcion(np.array([[funcion(np.array([[X[0],funcion(np.array([X[1]]),peso_not)]]),peso_and),
                         funcion(np.array([[funcion(np.array([X[0]]), peso_not),X[1]]]),peso_and)]]), peso_or))
X = np.array([0.,1.])
print(funcion(np.array([[funcion(np.array([[X[0],funcion(np.array([X[1]]),peso_not)]]),peso_and),
                         funcion(np.array([[funcion(np.array([X[0]]), peso_not),X[1]]]),peso_and)]]), peso_or))
X = np.array([0.,0.])
print(funcion(np.array([[funcion(np.array([[X[0],funcion(np.array([X[1]]),peso_not)]]),peso_and),
                         funcion(np.array([[funcion(np.array([X[0]]), peso_not),X[1]]]),peso_and)]]), peso_or))


Entradas
[[1 1]
 [1 0]
 [0 1]
 [0 0]]
Salidas
0.0
1.0
1.0
0.0
